#!/usr/bin/env bash

apt-get update

apt-get install -y ack-grep
apt-get install -y aspell
apt-get install -y automake
apt-get install -y build-essential
apt-get install -y byacc
apt-get install -y checkinstall
apt-get install -y cmake
apt-get install -y cython
apt-get install -y emacs24
apt-get install -y fabric
apt-get install -y flex
apt-get install -y gdb
apt-get install -y git
apt-get install -y git-extras
apt-get install -y gunicorn
apt-get install -y ipython
apt-get install -y libatlas-base-dev
apt-get install -y libboost-all-dev
apt-get install -y libgflags-dev
apt-get install -y libgoogle-glog-dev
apt-get install -y libgtest-dev
apt-get install -y libhdf5-serial-dev
apt-get install -y libleveldb-dev
apt-get install -y liblmdb-dev 
apt-get install -y liblmdb-dev 
apt-get install -y libopencv-dev
apt-get install -y libprotobuf-dev
apt-get install -y libsnappy-dev
apt-get install -y libssl-dev
apt-get install -y libtbb-dev
apt-get install -y libtool
apt-get install -y lsb-release
apt-get install -y mosh
apt-get install -y pkg-config
apt-get install -y protobuf-compiler
apt-get install -y python-boto
apt-get install -y python-falcon
apt-get install -y python-numpy
apt-get install -y python-opencv
apt-get install -y python-protobuf
apt-get install -y python-requests
apt-get install -y python-scikits-learn
apt-get install -y python-setuptools
apt-get install -y python-skimage
apt-get install -y python-thrift
apt-get install -y python-yaml
apt-get install -y screen
apt-get install -y silversearcher-ag
apt-get install -y thrift-compiler
apt-get install -y unzip
apt-get install -y zip
apt-get install -y vim
apt-get install -y dstat
apt-get install -y python-skimage
apt-get install -y redis-server
apt-get install -y python-redis
apt-get install -y ipython-notebook
